version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql-e-commerce
    ports:
      - '5425:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    restart: always

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

